### ISSUE TITLE
txt encoding?

### ISSUE THREAD

**Issue by matchlesswei** [kunlubrain/searchdb_ner#1]
@kunlubrain Do you know which encoding is used when generating txt?
When using UTF-8 to encode, I got the following string:
<img width="752" alt="Screenshot 2022-05-27 at 09 33 26" src="https://user-images.githubusercontent.com/23156705/170655007-24612e1b-ec48-4a1f-ac26-4e1b4432ccaa.png">

**Comment by kunlubrain** [comment]
oh, my encoding is not correct, let me fix this. Will let you know when it's done.

**Comment by kunlubrain** [comment]
A **new** file called `searchdb_ner_trainingset_bio.txt` is uploaded, which is in **BIO** format. This might make it easier for you, since you do not need to preprocess it. 

The encoding format is `utf-8`.

**Comment by kunlubrain** [comment]
@matchlesswei  FYI
