### ISSUE TITLE
Postprocess the NER prediction results

### ISSUE THREAD

**Issue by kunlubrain** [kunlubrain/searchdb_ner#2]
The prediction result of our NER model needs to be processed to return a list of entities. Each entity is structured as such:

```python
class NamedEntity(BaseModel):
    start_pos: int
    end_pos: int
    tag: str
    probability: float
```

This list can include or ignore all those `O` tags, i.e. those O-entities are optional.

**Comment by matchlesswei** [comment]
I have added one field: text
Output looks like this:
<img width="1012" alt="Screenshot 2022-06-10 at 18 25 27" src="https://user-images.githubusercontent.com/23156705/173110392-5d69ff7a-bb63-40cf-84bb-3b4cefeb646a.png">

**Comment by kunlubrain** [comment]
DONE
