### ISSUE TITLE
Create the APIs to trigger the prediction

### ISSUE THREAD

**Issue by kunlubrain** [kunlubrain/searchdb_ner#3]
Using the trained NER model, we want to create one or more APIs to serve the model. 

Example request

```
POST /app/v1/ner/prediction?query=...
```

**Response**

```
{
   "error": "PLACEHOLDER MESSAGE",
   "prediction": {
       "entities": [
       ]
   }
}
```

**Comment by matchlesswei** [comment]
<img width="1532" alt="Screenshot 2022-06-21 at 21 26 44" src="https://user-images.githubusercontent.com/23156705/174882013-aa05ba48-c7c5-49d2-9d3b-ef4a21fddb3b.png">

**Comment by kunlubrain** [comment]
Great work!
DONE
